%PROJECTNAME%=@env CI_REPO_NAME
%PAGEICON%=docs/icon.webp
%USERNAME%=@env CI_REPO_OWNER
%CV%=%WEBSITE%
%WEBSITE%=https://%WEBPAGE%
%WEBPAGE%=@env LOCAL_DOMAIN
%REALNAME%=Chimmie Firefly
%CALCAGE%=@datimize 2006.07.31
%EMAIL%=gameplayer2019pl@tutamail.com
%MATRIX%=matrix.to/#/@gameplayer:catgirl.cloud
%FEDIVERSE%=tech.lgbt/@gameplayer

