%PROJECTNAME%=@env GIT_PROJECT_NAME
%PAGEICON%=docs/icon.webp
%USERNAME%=@env GIT_USERNAME
%CV%=%WEBPAGE%/resume
%WEBPAGE%=@env GIT_WEBPAGE
%REALNAME%=Chimmie Firefly
%CALCAGE%=@datimize 2006.07.31
%EMAIL%=gameplayer2019pl@tutamail.com
%MATRIX%=matrix.to/#/@gameplayer:catgirl.cloud
%FEDIVERSE%=tech.lgbt/@gameplayer
